### ISSUE TITLE
Enable rebuild queue by default

### ISSUE THREAD

**Issue by fvennetier** [open-io/puppet-openiosds#151]
When an object is uploaded, and this object only partially satisfies the storage policy, an event is emitted. With the current default configuration, this event is just dropped. I suggest enabling the `rebuild` option by default [here](https://github.com/open-io/puppet-openiosds/blob/f678fa15f53edac20e507c742ff13db38cf5fc61/manifests/oioeventagent.pp#L26) and use the same queue as `queue_url` by default.

**Comment by jkasarherou** [comment]
done in #155
