### ISSUE TITLE
Unnecessary parameter in oio-event-agent

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/puppet-openiosds#4]
Using puppet to deploy oio-event-agent, an unnecessary parameter is set in gridinit.conf.d folder for oio-vent-agent :  `--chlid-req`

```
-bash-4.2$ /usr/bin/oio-cluster-agent --child-req -s OIO,local,sds-agent,0 /etc/oio/sds/sds-agent-0/sds-agent-0.conf
/usr/bin/oio-cluster-agent: unrecognized option '--child-req’
```

This option is now set by default, you can remove it.

**Comment by racciari** [comment]
Removed d2bd634ceb3d7d712905f43323d8269b1843dc30
