### ISSUE TITLE
Cannot create /run/oio/sds

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/puppet-openiosds#53]
During the first run of a puppet apply on a Debian 8 with the 16.10 repository, I have this error:

`Error: Cannot create /run/oio/sds; parent directory /run/oio does not exist
Error: /Stage[main]/Main/Openiosds::Namespace[FREE]/File[/run/oio/sds]/ensure: change from absent to directory failed: Cannot create /run/oio/sds; parent directory /run/oio does not exist`

Disappear on the second launch.

**Comment by racciari** [comment]
I think the bug is fixed f76aceada224fd036eba9ec7074750d7c3ce6813
