### ISSUE TITLE
replicator conf file is invalid when working without ECD

### ISSUE THREAD

**Issue by cdedeurwaerder** [open-io/puppet-openiosds#54]
In this template https://github.com/open-io/puppet-openiosds/blob/master/templates/replicator.conf.erb
if you don't specify ECD url in source / destination block, there is a trailing "," at the end of "ns" line which cause "InvalidJsonException".

Regards,

Chris.

**Comment by jkasarherou** [comment]
fixed in 932ff4a7bd52e1b342f3e233ca1d223f56fc074f
