### ISSUE TITLE
Set udp_allowed as a boolean field

### ISSUE THREAD

**Issue by vdombrovski** [open-io/puppet-openiosds#93]
Currently udp_allowed is validated against a string, yet it takes only values true/false. Wouldn't it be better to validate it against a boolean then?

https://github.com/open-io/puppet-openiosds/blob/master/manifests/namespace.pp#L29

**Comment by racciari** [comment]
I don't remember exactly the reason but it doesn't work when casting it to boolean, either printing the value, or when it's used False. The best way to validate it would be to test it against an enum of valid strings.

**Comment by racciari** [comment]
won't fix.
